(let ((dir "~/repo/emacs/"))
  (load (concat dir "init-core"))
  (load (concat dir "init-utils"))
  (load (concat dir "init-backup"))
  (load (concat dir "init-calendar-sv"))
  (load (concat dir "init-spelling"))
  (load (concat dir "init-org"))
  (load (concat dir "init-projectile"))
  (load (concat dir "init-dired"))
  (load (concat dir "init-lsp"))
  (load (concat dir "init-lsp-python"))
  (load (concat dir "init-lsp-yaml"))
  (load (concat dir "init-magit"))
  (load (concat dir "init-writing"))
  (load (concat dir "init-web-html"))
  (load (concat dir "init-css"))
  (load (concat dir "init-json"))
  (load (concat dir "init-markdown"))
  (load (concat dir "init-gnuplot"))
  (load (concat dir "init-doom"))
  (load (concat dir "init-server"))
  (load (concat dir "init-keybindings")))

(set-frame-font "Fira Code-12")
(setq-default line-spacing 4)

(add-to-list 'org-refile-targets '("fun.org" :maxlevel . 2) 'append)

(defun my-after-init-hook-setup ()
  (progn
    (org-agenda nil " ")
    (toggle-frame-maximized)))
(add-hook 'after-init-hook #'my-after-init-hook-setup)