(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)  ; prefix key
(global-set-key (kbd "<f5> l") 'toggle-truncate-lines)
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "C-c i u") 'counsel-unicode-char)
(global-set-key (kbd "C-c l") 'org-store-link)
(global-set-key (kbd "C-c w f") 'my-copy-filename)
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "C-t") 'counsel-company)
(global-set-key (kbd "C-x 2") 'my-split-window-horizontally)
(global-set-key (kbd "C-x 3") 'my-split-window-vertically)
(global-set-key (kbd "C-x C-d") 'dired)
(global-set-key (kbd "C-x M-g") 'magit-dispatch)
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-x k") 'my-kill-this-buffer)
(global-set-key (kbd "C-ä")  'ivy-switch-buffer)
(global-set-key (kbd "C-ö")  'mode-line-other-buffer)
(global-set-key (kbd "M-j") 'avy-goto-char-timer)
(global-set-key (kbd "M-o") 'ace-window)
(global-set-key (kbd "M-x") 'counsel-M-x)
