My Emacs configuration.

* init.example.el
Example of what an init file might look like.
* Notes on use-package
Some notes about the use of use-package.
** :init
Code in :init is executed before module is loaded. It should not break
things even if the module fails to load.

Keep :init as small as possible, i.e. put as much as possible in the
:config block, this can improve startup time.
** :ensure
Using :ensure nil for built-in packages.
* calendar-sv.el
Calendar, date, and time config with a few Swedish tweaks.

The function =sv-easter= was pretty much copied from https://bigwalter.net/daniel/elisp/sv-kalender.el
* theme-doom.el
Emacs doom-theme with doom-modeline.
* keybindings.el
Global keybindings.
* org.el
Org-mode.

Note sure about
: (setq org-agenda-prefer-last-repeat t)
Removed it for now.

See:
- https://orgmode.org/manual/Export-settings.html
- https://orgmode.org/manual/The-export-dispatcher.html
* python.el
Basic python setup using pyvenv, "Python virtual environment interface".

See:
- https://docs.python.org/3/library/venv.html
* server.el
Emacs server.
